### PR TITLE
Import SeedUnityVRKit v0.1.0-alpha.

### LINKED ISSUE #7: Add mediapipe MacOS plugin

### PR DESCRIPTION
**Pull request by henryouly**
Import resources from [SeedUnityVRKit v0.1.0-alpha](https://github.com/SeedV/SeedUnityVRKit/tree/v0.1.0-alpha).
* Mediapipe plugin (`Packages/...`) supporting MacOS Intel and Apple SOC
* Scripts for running mediapipe graph (`Assets/Scripts/...`)
* Holistic model data (`Assets/StreamingAssets/...`)
* OpenCV plugin for SolvePnP (`Assets/Plugins/...`)
* Face mesh 3D points data for SolvePnP (`Assets/Resources/...`)

Only added files, scene update will be in the next integration CL (https://github.com/SeedV/SeedAvatarStudio/commit/93751b0d7bd2185850561e3c1ee086fd643a54b9)

Demo branch: https://github.com/SeedV/SeedAvatarStudio/tree/henryouly-mediapipe-dev

Close #7

### CODE REVIEW

**Comment by superkudo** [comment]
The scripts files suggest  move into src folders,  consider add namespace SeedAvatar and moving all the source files of this  into a subdir

**Comment by superkudo** [comment]
I local used changed scenes to run, it not work but not error,  I guess the HolisticTracker component param HolisticLandmarkListAnnotationController is none,   how to set this param.
image
image

**Comment by henryouly** [comment]
You can follow https://github.com/SeedV/SeedAvatarStudio/commit/93751b0d7bd2185850561e3c1ee086fd643a54b9 to avoid requiring a `HolisticLandmarkListAnnotationController` instance for local testing.

Also - I think the reason why it doesn't work for you might be the [opencvplugin](https://github.com/SeedV/SeedAvatarStudio/tree/henryouly-mediapipe/Assets/Plugins) bundle is currently built with arm64 arch. You may want to either rebuild the plugin, or disable relevant code in https://github.com/SeedV/SeedAvatarStudio/blob/henryouly-mediapipe/Assets/Src/Scripts/Animator/UpperBodyAnimator.cs

**Comment by superkudo** [comment]
I rebuild the opencvplugin bundle , It seems only header move with my pose（delay 10s）, body always stay 'T' pose with a error log
image

**Comment by henryouly** [comment]
The delay needs some more investigation. I think it might be the current rendering effects are more complex, but it could also because of using URP. I can also see a sensible slow down, although not as much as 10s.

MthDefRef error is a separated issue I also have. It was caused by the new SSU model doesn't have the mouth bone defined in the same way as original UnityChan model. Need some research on how to control mouth opening in the new model and update `UpperBodyAnimator`.

Body doesn't move is also expected. I haven't implemented the code to synchronize arm and hand movement. Only the head rotation and mouth is movable now (head rotation also has some issue with SSU model)

Anyway, I think we should first put the pieces together and then further investigate if using a SSU model is the right solution.

**Comment by superkudo** [comment]
I see ,LGTM

**Review by superkudo — APPROVED** [review]

**Comment by wixette** [comment]
Agree. It makes sense to put SeedUnityVRKit in and then solve the issues that Henry has already been observing. You can also log and track the know problems by creating issues in this project.

**Pull request merged**
